---
# NB: don't set `language: haskell` here
# See https://github.com/hvr/multi-ghc-travis for more information
 
notifications:
  email:
    - ibotty+travis@ibotty.net
  on_success: never
  on_failure: always

env:
 - GHCVER=7.6.1
 - GHCVER=7.6.2
 - GHCVER=7.6.3
 #- GHCVER=7.8.2
 - GHCVER=head

matrix:
  allow_failures:
    - env: GHCVER=head

before_install:
 - sudo add-apt-repository -y ppa:hvr/ghc
 - sudo apt-get update
 - sudo apt-get install cabal-install-1.18 ghc-$GHCVER
 - export PATH=/opt/ghc/$GHCVER/bin:$PATH

install:
 - cabal-1.18 update cprng-aes-effect crypto-random-effect
 - cabal-1.18 install --only-dependencies --enable-tests cprng-aes-effect crypto-random-effect

script:
 - cabal-1.18 configure --enable-tests -v2 cprng-aes-effect crypto-random-effect
 - cabal-1.18 build cprng-aes-effect crypto-random-effect
 - cabal-1.18 test cprng-aes-effect crypto-random-effect
 - cabal-1.18 check cprng-aes-effect crypto-random-effect
 - cabal-1.18 sdist cprng-aes-effect crypto-random-effect
